name: Test workflows

on:
  # This rule allows releases to be prepared from the Actions UI or Actions API
  workflow_dispatch:
    inputs:
      branch:
        description: Sample branch name
        default: 'JIRA-123/foo-bar-baz'
        required: false

jobs:
  test:
    environment: "Test Environment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Makes current date available as `${{ steps.date-output.outputs.today }}`
        id: date-output
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - name: Show date output
        id: date-output-show
        run: echo "Got date ${{ steps.date-output.outputs.today }}"

      - name: Makes current date available as `$today`
        id: date-env
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Show date env
        id: date-env-show
        run: echo "Got date $today"
        
      - name: Parse input
        id: parse-input
        run: |
          branch=${{ github.event.inputs.branch }}
          jira=$(echo ${{ github.event.inputs.branch }} | awk -F '/' '{print $1}')
          desc=$(echo ${{ github.event.inputs.branch }} | awk -F '/' '{print $2}' | tr '\-\_\/' ' ')
          echo "::set-output name=branch::$branch"
          echo "::set-output name=jira::$jira"
          echo "::set-output name=desc::$desc"
          echo "::set-output name=title::[$jira] $desc)"

      - name: Show input
        id: input-show
        run: |
          echo "Got JIRA: ${{ steps.parse-input.outputs.jira }}"
          echo "Got desc: ${{ steps.parse-input.outputs.desc }}"
          echo "Got title: ${{ steps.parse-input.outputs.title }}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      
      - name: Dump secrets context
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: echo "$SECRETS_CONTEXT"
      
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
