name: Test workflows

on:
  # This rule allows releases to be prepared from the Actions UI or Actions API
  workflow_dispatch:
    inputs:
      name:
        description: PR Name
        default: 'foobar'
        required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Makes current date available as `${{ steps.date.outputs.today }}`
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - name: Show input
        id: input-show
        run: echo "Got input ${{ github.event.inputs.foo }}"

      - name: Open PR
        uses: repo-sync/pull-request@v2.5
        id: pr
        with:
          source_branch: pr_number
          destination_branch: main
          pr_title: "${{ github.event.inputs.name }} ${{ steps.date.outputs.today }}"
          pr_body: test
          pr_label: "release"
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"